import type { Metadata } from "next";
import { lato } from "./fonts";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${lato.variable} ${lato.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
