[phases.setup]
nixPkgs = ["nodejs_latest"]
nixpkgsArchive = "nixpkgs-unstable"

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["npx tsc && npx tsc-alias"]

[start]
cmd = "npx prisma generate && npx prisma migrate deploy && node dist/src/index.js"
